#!/usr/bin/env ruby

git_bundles = [ 
  "git://github.com/vim-scripts/Gist.vim.git",
  "https://github.com/tpope/vim-fugitive.git",
  "https://github.com/scrooloose/nerdtree",
  "https://github.com/vim-scripts/taglist.vim.git",
  "https://github.com/othree/html5.vim.git",
  "https://github.com/vimoutliner/vimoutliner",
  "https://github.com/vimwiki/vimwiki.git",
  "https://github.com/samsonw/vim-task",
  "https://github.com/mattn/emmet-vim",
  "https://github.com/msanders/snipmate.vim",
  "https://github.com/vim-scripts/project.tar.gz"
  "https://github.com/mustache/vim-mustache-handlebars.git",
  "https://github.com/altercation/solarized",
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
